# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

acoustic_guitars = Category.create(name: "Acoustic Guitars", electric: false)
pianos = Category.create(name: "Pianos", electric: false)
drums = Category.create(name: "Drums", electric: false)
bass = Category.create(name: "Bass", electric: true)
electric_guitars = Category.create(name: "Electric Guitars", electric: true)
keyboards = Category.create(name: "Keyboards", electric: true)


fender_fa_concert = Product.create(name: "Fender FA-135CE Concert Acoustic-Electric Guitar", used: false, price: 209.99, description: "The Fender FA-135CE Concert Acoustic Guitar is built on the concert-style platform for a sleek, modern design. The laminated spruce top features X-bracing for bright, punchy tone, ideal for lead guitar. The neck is nato, and the back and sides are laminated basswood-both tonewoods known for letting the mid and high frequencies sing out.
Thanks to the basswood back and sides, the Fender FA-135CE is very light, avoiding strain to your neck or back during prolonged playing. The chrome tuners offer precision tuning. The guitar also features an impressive electronics system, featuring the Fishman ION-T preamp and built-in chromatic tuner, which provides lightning-fast tuning and amplification. The preamp features a volume dial, phase and contour buttons, and a tuner power button.
    The FA-135CE is fashioned with a gloss polyurethane finish, aged fretboard and body bindings, and a white concentric ring rosette that offers a striking contrast, and an appearance as beautiful as its sound.", brand: "Fender", image: "https://i.ibb.co/WvHYD6L/L44601000003000-02-2000x2000.jpg", third_image: "https://i.ibb.co/hYssmkN/L44601000003000-04-2000x2000.jpg", category_id: acoustic_guitars.id)

yamaha_dreadnought = Product.create(name: "Yamaha FG830 Dreadnought Acoustic Guitar  Natural", used: false, price: 339.99, description: "	
    Rich overtones and improved sustain thanks to the rosewood back and sides deliver improved sound through greater ‘depth’. The appearance, with abalone inlay around the sound hole, is more luxurious and an obvious step-up. Specially Developed Scalloped BracingYamaha's modern FG has louder and stronger sound in the low- to mid-ranges, thanks to cutting-edge acoustic analysis technology developed by the Yamaha R&D Division. Yamaha’s engineers have achieved this sound by utilizing analysis and simulation to arrive at the best bracing design without depending on tradition or guesswork. This analysis led to the development of the new scalloped bracing pattern, an ideal acoustic structure that maintains the durability of the top board while bringing out the most sound the Yamaha FG has to offer.",
brand: "Yamaha", image: "https://i.ibb.co/JQNR0Qj/J33498000001000-02-2000x2000-front.jpg", back_image: "https://i.ibb.co/BrFRJW2/J33498000001000-03-2000x2000.jpg", third_image: "https://i.ibb.co/3YfMP78/J33498000001000-04-2000x2000.jpg", category_id: acoustic_guitars.id )

fender_california_newporter = Product.create(name:"Fender California Newporter Player Acoustic-Electric Guitar  Ocean Teal Satin", used: false, price: 429.99, description: "Follow your musical vision and express yourself with the unique Newporter Player. The exclusive medium-sized Newporter shape gives it a balanced voice that’s both articulate and powerful, perfect for backing up any singer. Designed for performing, the fully-painted gloss metallic solid spruce top, mahogany back and sides, matching painted 6-in-line headstock and crème binding give this guitar a shot of electrifying style.
Unconventional to the core, the Newporter Player is definitely something different and exciting. The same no-compromise attitude that gives the Newporter Player its uniquely killer vibe extends to every aspect of its construction. It features optimized bracing for reduced mass and superior resonance, a Graph Tech NuBone nut and saddle for greater sustain and a Fishman preamp system that makes it easy to plug in without sacrificing the guitar’s natural sound. Its lightweight mahogany neck features a comfortable, easy-to-play, slim-taper “C”-shaped profile suitable for any playing style, and its laurel fingerboard and bridge further augment this instrument’s vibrant tone.",
 brand: "Fender", image: "https://i.ibb.co/NygBcsw/K47867000007000-02-500x500-front.jpg", third_image: "https://i.ibb.co/cxFqcYM/K47867000007000-04-500x500.jpg", category_id: acoustic_guitars.id)

yamaha_fs830 = Product.create(name: "Yamaha FS830 Small Body Acoustic Guitar  Dusk Sun Red", used: false, price: 339.99, description: "	
    The FS830 offers rich overtones, greater depth and improved sustain thanks to the rosewood back and sides and special bracing. The appearance, with abalone inlay around the sound hole, is more luxurious and an obvious step-up. The small and thin body is perfect not only for female/young players but for intermediate to upper level finger-picking style players.
    This FS has louder and stronger sound in the low- to mid-ranges, thanks to cutting-edge acoustic analysis technology developed by the Yamaha R&D Division. Yamaha’s engineers have achieved this sound by utilizing analysis and simulation to arrive at the best bracing design without depending on tradition or guesswork. This analysis led to the development of the new scalloped bracing pattern, an ideal acoustic structure that maintains the durability of the top board while bringing out the most sound the Yamaha FS has to offer.", brand: "Yamaha", image: "https://i.ibb.co/wYvHfk9/J37423000002000-02-2000x2000-front.jpg", third_image: "https://i.ibb.co/DbGp9zB/J37423000002000-04-500x500.jpg", category_id: acoustic_guitars.id)

fender_california_malibu = Product.create(name: "Fender California Malibu Player Acoustic-Electric Guitar  Arctic Gold", used: false, price: 429.99, description: "True creativity requires something new, something like the inspiring sound and feel of the Malibu Player. The exclusive small-body shape’s short scale gives it a slightly slinkier feel, encouraging you to reach for new chords and melodies. It looks as stunning as it sounds, with a gloss metallic solid spruce top and mahogany back and sides, as well as a matching painted 6-in-line headstock and crème binding giving it a shot of electrifying attitude. The bold style and balanced, articulate sound make the Malibu Player a natural partner on stage and in the studio.
    The same no-compromise attitude that gives the Malibu Player its uniquely killer vibe extends to every aspect of its construction. It features optimized bracing for reduced mass and superior resonance, a Graph Tech NuBone nut and saddle for greater sustain, and a Fishman preamp system that makes it easy to plug in without sacrificing the guitar’s natural sound.
    The Malibu Player's lightweight mahogany neck features a comfortable, easy-to-play, slim-taper C-shaped profile suitable for any playing style, and its laurel fingerboard and bridge further augment this instrument’s vibrant tone. With superb playability, distinctive looks and unmistakable Fender vibe, the Malibu Player is an instrument for a new generation of fearless players.", brand: "Fender", image: "https://i.ibb.co/7b9pGLt/K47864000004000-02-2000x2000.jpg", back_image: "https://i.ibb.co/Y2GvnF9/K47864000004000-03-2000x2000.jpg", third_image: "https://i.ibb.co/dBN3PYH/K47864000004000-04-2000x2000.jpg", category_id: acoustic_guitars.id)

fender_player_stratocaster = Product.create(name: "Fender Player Stratocaster Maple Fingerboard Electric Guitar  3-Color Sunburst", used: false, price: 799.99, description: "Over the decades, players have been continually inspired by the sound of a Strat. From the clarity of the high end, through the gut punch of the mids and the solid lows, it's a sound that's helped define what an electric guitar should be—versatile enough for any style and broad enough for any player to find an individual voice. This Player Series Stratocaster puts all of the classic features of the Strat at your fingertips while adding a modern edge, including a modern neck profile, medium-jumbo frets and a freshly redesigned 2-point fulcrum vibrato bridge. With a beautiful gloss finish over a solid alder body, a 22-fret pau ferro fingerboard with a contemporary 9.5 inch radius for easy bending, the Player Series Stratocaster is primed and ready to carry you along your musical voyage.", brand: "Fender", image: "https://i.ibb.co/B4h6S7X/L21533000005000-02-2000x2000.jpg", category_id: electric_guitars.id)

gibson_les_paul_studio = Product.create(name: "Gibson Les Paul Studio Electric Guitar  Wine Red", used: false, price: 1599.00, description: "The Les Paul Studio embodies the essential Les Paul features with enhancements for playability and tonal versatility. The rosewood fingerboard and slim taper mahogany neck provide effortless playability and comfort. The 490R and 498T pickups provide tight, high-output humbucking performance and the two push-pull pots offer additional coil-tapping options.", brand: "Gibson", image: "https://i.ibb.co/NgvjmQJ/L54490000001000-02-2000x2000.jpg", back_image: "https://i.ibb.co/NWhmYBx/L54490000001000-01-2000x2000.jpg", third_image: "https://i.ibb.co/jk2cDp1/L54490000001000-06-2000x2000.jpg", category_id: electric_guitars.id)

epiphone_extura_prophecy = Product.create(name: "Epiphone Extura Prophecy Electric Guitar Purple Tiger Aged Gloss", used: false, price: 899.00, description: "The Epiphone Prophecy Extura combines the elegance of the Explorer—Gibson's radical electric solidbody from 1958—and the original Epiphone Prophecy from 2001. The Prophecy Extura puts all 24 frets within reach thanks to its modern contoured heel, making this a suitable shredder for the technically-inclined soloist.
The Extura features a mahogany body with a flame maple AAA veneer top. A thin coat of aged vintage gloss allows the body to breathe and guarantees that this guitar will age gracefully. The mahogany neck has a SlimTaper asymmetrical profile that's both ergonomic and built for speed. The ebony fretboard adds instant class and looks great with block and triangle pearloid/abalone inlays.
Epiphone spec'd the Extura with a pair of proprietary Fishman Fluence humbuckers that are hum and noise free, making this an ideal recording guitar. Three voicing options can be selected with push/pull pots: modern active high output, coil tap for classic PAF-style humbucker, and coil split for slightly overwound single-coil sounds. This is one versatile instrument.",  brand: "Epiphone", image: "https://i.ibb.co/vZRmPDr/L78220000002000-02-2000x2000.jpg", back_image: "https://i.ibb.co/3vPPWD8/L78220000002000-01-2000x2000.jpg", category_id: electric_guitars.id )

epiphone_usa_casino = Product.create(name: "Epiphone USA Casino Hollowbody Electric Guitar  Vintage Burst", used: false, price: 2999.00, description: "Now made in the U.S. for the first time in over 50 years, the new Epiphone Casino features a classic maple and poplar body with a nitro lacquer finish. The USA Collection Epiphone Casino also features hand-wired electronics with Orange Drop capacitors and Gibson USA P-90 Dogear single-coil pickups. 
Since its introduction in 1961, the Epiphone Casino has been the choice of countless legendary musicians.", brand: "Epiphone", image: "https://i.ibb.co/xGbwh02/L76765000001000-02-2000x2000.jpg", third_image: "https://i.ibb.co/X4yzX3R/L76765000001000-04-2000x2000.jpg", category_id: electric_guitars.id)

gibson_les_paul_axcess = Product.create(name: "Gibson Les Paul Axcess Custom Floyd Rose Electric Guitar Ebony", used: false, price: 5499.00, description: "The Gibson Les Paul Axcess Custom electric guitar reimagines the iconic original. Featuring the Apex headstock for added strength, redesigned contours for added comfort and fretboard access and powerful coil-tapped humbuckers, this Les Paul Custom delivers on style, power and versatile tone. A Floyd Rose tremolo and locking nut provide tuning stability during the craziest dive bombs, while the solid ebony fingerboard retains clarity in every note and chord. At its core, the Les Paul Axcess is a Custom Shop Black Beauty with show-stopping looks, pearl appointments and gold hardware.", brand: "Gibson", image: "https://i.ibb.co/tbQFTbk/L78502000001000-02-2000x2000.jpg", back_image: "https://i.ibb.co/wKS1fj2/L78502000001000-03-2000x2000.jpg", category_id: electric_guitars.id)

pearl_export = Product.create(name: "Pearl Export New Fusion 5-Piece Drum Set with Hardware Mirror Chrome", used: false, price: 879.00, description: "	
    Like a legendary group or solo act whose mystique only grew during inactivity, the Export Series from Pearl is back and ready to help you take your act on the road. Unlike that aged group or musician, Pearl Export has only improved with age. Offering new hardware features, SST shell construction and suspended mounts, these Export drums are better than you remember them. The 6-ply poplar and mahogany shells churn out balanced attack and full tone, while the high-end hardware will make your trip down memory lane a pleasant one.
    Pearl's updated Export Series offers a sonically advanced recipe of strategically arranged plies of premium wood to maximize frequency response of every component. As with all Pearl drums, each shell is formed from our legendary SST construction process that uses extreme heat, Precision-cut scarf joints, proprietary Acoustiglue and over 1000lb. of hydraulic pressure to create the ultimate acoustic air chamber.
    Further emphasizing Pearl's sound first philosophy are the new lugs specifically designed for Export with sound-enhancement in mind. Designed for minimal shell interaction, they have a small footprint and low-mass for maximum resonance and sustain. Their bold look is modern but with a nod to lugs from Pearl's past.", brand: "Pearl", image: "https://i.ibb.co/9WLZ01n/H94538000008000-00-2000x2000.jpg", category_id: drums.id)

yamaha_rydeen = Product.create(name: "Yamaha Rydeen 5-Piece Shell Pack with 22 in. Bass Drum  Burgundy Glitter", used: false, price: 419.99, description: "Rydeen the God of Thunder is back to inspire young drummers with quality sound and solid hardware. This shell pack utilizes genuine Yamaha tom holders for simple adjustments and features solid and glitter finishes. Yamaha Hardware allows creative set up variations and grows with the needs of a younger player. Rydeen quality will ensure your young drummer spends more time playing and less time tuning or adjusting less expensive alternatives.", brand: "Yamaha", image: "https://i.ibb.co/sPwySnB/J50178000002000-00-2000x2000.jpg", category_id: drums.id)

yamaha_stage = Product.create(name: "Yamaha Stage Custom Birch 5-Piece Shell Pack with 22 inch Bass Drum Raven Black", used: false, price: 709.99, description: "This Yamaha Stage Custom birch drum shell pack is also great for the beginner or the working professional. The staggered diagonal seam allowed Yamaha to build a thin drum shell that will start round and stay round. The low-mass lugs lets the shell vibrate for superb tone and sustain. Yamaha's Air Seal System used for drum shell construction ensures each and every Yamaha drum shell is of uniform thickness and is perfectly round to achieve superior tone quality and durability. Features a beautiful high-gloss lacquer finish.", brand: "Yamaha", image: "https://i.ibb.co/jhYz1MH/J07117000005000-00-2000x2000.jpg", category_id: drums.id)

tama_club = Product.create(name: "TAMA Club-JAM Suitcase 3-Piece Shell Pack with 16 in. Bass Drum Indigo Sparkle", used: false, price: 399.99, description: "The Club-JAM Suitcase kit features the ultimate portability, and is the perfect addition to the Club-JAM family. The bass drum can be divided into two pieces, allowing the tom tom and floor tom to be stored inside for easy transportation by utilizing a specially designed bag (DSS36LJ, sold separately). The 15 inch deep, 16 inch diameter bass drum offers a big sound in a compact size. This model offers an authentic drum sound with the convenience of single case portability.", brand: "Tama", image: "https://i.ibb.co/TPqRC2y/L81900000001000-02-2000x2000.jpg", category_id: drums.id)

pearl_music_city = Product.create(name: "Pearl Music City Custom Masters Maple Reserve Double Bass Shell Pack Mirror Chrome", used: false, price: 5318.40, description: "Featuring 4-ply Maple reinforcement rings, Masters Maple Reserve is a natural choice for the most discerning musical pallet. This classic integration increases shell stability and tonal control, delivering rich, sustained lows and lively sonic punch. The MRV Series uses Premium North American Maple veneers from our exclusive Masterworks supply vault, the thin, 4-ply shell configuration (with reinforcement rings).
For over 40 years, Pearl’s exclusive USA Artist Custom shop has been collaborating with some of the most illustrious names in drumming to handcraft personal touring kits; featured on the largest live show stages across the world. Pearl's new Music City Custom Series now allows you to experience the same level of service and pride, by owning an exclusive kit precision CNC drilled and fully assembled at their custom shop facility within Pearl’s USA corporate headquarters in Nashville, TN.", brand: "Pearl", image: "https://i.ibb.co/PNNzc9K/J53591000001000-00-2000x2000.jpg", category_id: drums.id)